Repository mn-pollinators/buzz-about, pull requests merged in 2020-07, with the labels that each got.

#68 List students
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/firebase.service.ts
  src/app/hill-background/hill-background.component.scss
  src/app/home/home.component.html
  src/app/joined-students/joined-students.component.html
  src/app/joined-students/joined-students.component.scss
  src/app/joined-students/joined-students.component.spec.ts
  src/app/joined-students/joined-students.component.ts
  src/app/session-lobby/session-lobby.component.html
  src/app/session-lobby/session-lobby.component.scss
  src/app/session-lobby/session-lobby.component.spec.ts
  src/app/session-lobby/session-lobby.component.ts
  src/app/session-page-test/session-page-test.component.html
  src/app/session-page-test/session-page-test.component.ts
  src/app/student-login/student-login.component.html
  src/app/student-login/student-login.component.ts
  src/app/teacher-session.service.spec.ts
  src/app/teacher-session.service.ts
Labels: large display

#81 Add art assets to AR view
  .vscode/settings.json
  firebase-test-data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  firebase-test-data/firestore_export/all_namespaces/all_kinds/output-0
  src/app/ar-view/ar-view.component.scss
  src/app/ar-view/ar-view.component.ts
  src/app/play-round/play-round.component.html
  src/app/play-round/play-round.component.scss
  src/app/play-round/play-round.component.ts
  src/app/rounds/example.round.spec.ts
  src/app/rounds/example.round.ts
  src/app/rounds/round.ts
Labels: AR, assets

#83 Auth service automatic anonymous sign in
  src/app/auth.service.ts
  src/app/session-page-test/session-page-test.component.ts
  src/app/session-test/session-test.component.html
  src/app/session-test/session-test.component.ts
  src/app/student-login/student-login.component.ts
Labels: authentication

#90 Add interact button to play-round
  firestore.rules
  src/app/firebase.service.ts
  src/app/play-round/play-round.component.html
  src/app/play-round/play-round.component.scss
  src/app/play-round/play-round.component.ts
  src/app/round.ts
  src/app/session-test/session-test.component.html
  src/app/session-test/session-test.component.ts
  src/app/student-round.service.spec.ts
  src/app/student-round.service.ts
Labels: AR
